version: '3'

services:    

   anuncios-api:
      container_name: anuncios-api
      build: .
      ports: 
         - "5000:80"
      extra_hosts:
         - "localhost:@ipLocal"
      depends_on:
         - sql-server-anuncios-db

   sql-server-anuncios-db:     
      container_name: sql-server-anuncios-db     
      image: microsoft/mssql-server-linux:2017-latest     
      ports:       
         - "1433:1433"     
      environment:       
         SA_PASSWORD: "sa!@1234"       
         ACCEPT_EULA: "Y"
